### ISSUE TITLE
dialog management model training error

### ISSUE THREAD

**Issue by hrit04** [Limechat/Simple-Hotel-Chatbot#5]
(venv) C:\Users\Hritam\Desktop\chatbot>rasa train
f:\anaconda_latest\lib\site-packages\rasa\utils\common.py:363: UserWarning: Loading domain from 'domain.yml' failed. Using empty domain. Error: 'The provided yaml file is invalid. You can use http://www.yamllint.com/ to validate the yaml syntax of your file.'
Training NLU model...
2020-07-04 16:19:41 INFO     rasa.nlu.training_data.training_data  - Training data stats:
2020-07-04 16:19:41 INFO     rasa.nlu.training_data.training_data  - Number of intent examples: 74 (12 distinct intents)
2020-07-04 16:19:41 INFO     rasa.nlu.training_data.training_data  -   Found intents: 'deny', 'book_room_all_details', 'CleanRoom', 'room_type', 'goodbye', 'affirm', 'book_room', 'book_n_rooms', 'greet', 'mood_unhappy', 'bot_challenge', 'mood_great'
2020-07-04 16:19:41 INFO     rasa.nlu.training_data.training_data  - Number of response examples: 0 (0 distinct responses)
2020-07-04 16:19:41 INFO     rasa.nlu.training_data.training_data  - Number of entity examples: 20 (2 distinct entities)
2020-07-04 16:19:41 INFO     rasa.nlu.training_data.training_data  -   Found entity types: 'num_rooms', 'room_type_name'
2020-07-04 16:19:41 INFO     rasa.nlu.model  - Starting to train component WhitespaceTokenizer
2020-07-04 16:19:41 INFO     rasa.nlu.model  - Finished training component.
2020-07-04 16:19:41 INFO     rasa.nlu.model  - Starting to train component RegexFeaturizer
f:\anaconda_latest\lib\site-packages\rasa\nlu\featurizers\sparse_featurizer\regex_featurizer.py:79: FutureWarning: Directly including lookup tables as a list is deprecated since Rasa 1.6.
  regex_pattern = self._generate_lookup_regex(table)
Traceback (most recent call last):
  File "f:\anaconda_latest\lib\site-packages\rasa\nlu\featurizers\sparse_featurizer\regex_featurizer.py", line 154, in _generate_lookup_regex
    f = open(lookup_elements, "r", encoding=rasa.utils.io.DEFAULT_ENCODING)
FileNotFoundError: [Errno 2] No such file or directory: '# intent:faqrestaurant'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "f:\anaconda_latest\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "f:\anaconda_latest\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\anaconda_latest\Scripts\rasa.exe\__main__.py", line 7, in <module>
  File "f:\anaconda_latest\lib\site-packages\rasa\__main__.py", line 92, in main
    cmdline_arguments.func(cmdline_arguments)
  File "f:\anaconda_latest\lib\site-packages\rasa\cli\train.py", line 76, in train
    additional_arguments=extract_additional_arguments(args),
  File "f:\anaconda_latest\lib\site-packages\rasa\train.py", line 50, in train
    additional_arguments=additional_arguments,
  File "f:\anaconda_latest\lib\asyncio\base_events.py", line 583, in run_until_complete
    return future.result()
  File "f:\anaconda_latest\lib\site-packages\rasa\train.py", line 91, in train_async
    file_importer, output_path, fixed_model_name
  File "f:\anaconda_latest\lib\site-packages\rasa\train.py", line 109, in handle_domain_if_not_exists
    file_importer, output=output_path, fixed_model_name=fixed_model_name
  File "f:\anaconda_latest\lib\site-packages\rasa\train.py", line 482, in _train_nlu_with_validated_data
    persist_nlu_training_data=persist_nlu_training_data,
  File "f:\anaconda_latest\lib\site-packages\rasa\nlu\train.py", line 90, in train
    interpreter = trainer.train(training_data, **kwargs)
  File "f:\anaconda_latest\lib\site-packages\rasa\nlu\model.py", line 191, in train
    updates = component.train(working_data, self.config, **context)
  File "f:\anaconda_latest\lib\site-packages\rasa\nlu\featurizers\sparse_featurizer\regex_featurizer.py", line 57, in train
    self._add_lookup_table_regexes(training_data.lookup_tables)
  File "f:\anaconda_latest\lib\site-packages\rasa\nlu\featurizers\sparse_featurizer\regex_featurizer.py", line 79, in _add_lookup_table_regexes
    regex_pattern = self._generate_lookup_regex(table)
  File "f:\anaconda_latest\lib\site-packages\rasa\nlu\featurizers\sparse_featurizer\regex_featurizer.py", line 157, in _generate_lookup_regex
    f"Could not load lookup table {lookup_elements}. "
ValueError: Could not load lookup table # intent:faqrestaurant. Please make sure you've provided the correct path.

**Comment by ChargedMonk** [comment]
Did you check your domain.yml file? Is it valid? If it is then I suggest looking at [this](https://rasa.com/docs/rasa/user-guide/building-assistants/) official tutorial for a cleaner faq section.

**Comment by tanujdhiman** [comment]
Exactly, you should check your domain.yml file. It is empty or not.

**Comment by tanujdhiman** [comment]
And don't remember to validate your domain.yml file through this link http://www.yamllint.com/
